var geojson_AssistenciaSocial = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "Lat": -23.260890, "Long": -45.906048, "Nome": "Casa de Oração Amor e Luz (Coal)", "Atividades": null, "Areas": "Orientação social e apoio material", "Area Princ": "Assistência Social", "Custo": null, "Endereco": "Rua Adolpho Goll, 22, Morumbi", "Horario": null, "Telefone": "(12) 3931-3407 \/ (12) 3939-2437", "Email": null, "Site": null, "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -45.906048, -23.26089 ] } },
{ "type": "Feature", "properties": { "Lat": -23.558242, "Long": -46.677825, "Nome": "Catalisa - Rede de Cooperação para a Sustentabilidade", "Atividades": "Gestão, elaboração, planejamento e execução de projetos de desenvolvimento comunitário e local sustentáveis, projetos de qualificação profissional, projetos educativos, artísticos e culturais. Setor público e privado. Consultoria para empresas na área de", "Areas": "Cultura, Meio Ambiente, Saúde, Educação, Assistência Social, Economia Solidária, Crianças e Adolescentes", "Area Princ": "Assistência Social", "Custo": "Definido por projeto", "Endereco": "Sede em São Paulo - Rua Cristiano Viana, 505, cjto 23", "Horario": "9:00 - 18:00", "Telefone": "33021605\/982610074", "Email": "mcarpin@catalisa.org.br", "Site": "www.catalisa.org.br", "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -46.677825, -23.558242 ] } },
{ "type": "Feature", "properties": { "Lat": -23.207091, "Long": -45.776564, "Nome": "Centro de Assistência Social Evangélica Palavra da Fé (Casepafe)", "Atividades": null, "Areas": "Orientação social e apoio material", "Area Princ": "Assistência Social", "Custo": null, "Endereco": "Rua A, 126, Santa Hermínia", "Horario": null, "Telefone": "(12) 3907-3967 \/ (12) 3907-9939", "Email": null, "Site": null, "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -45.776564, -23.207091 ] } },
{ "type": "Feature", "properties": { "Lat": -23.198117, "Long": -45.864286, "Nome": "Centro de Assistência Social Evangélico Palavra da Fé (Casepafe)", "Atividades": null, "Areas": "Orientação social e apoio material", "Area Princ": "Assistência Social", "Custo": null, "Endereco": "Rua Raul Ranco Martins, 616, Vila São Benedito", "Horario": null, "Telefone": "(12) 3923-1702", "Email": null, "Site": null, "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -45.864286, -23.198117 ] } },
{ "type": "Feature", "properties": { "Lat": -22.973088, "Long": -45.839888, "Nome": "Centro de Assistência Social Evangélico Palavra da Fé (Casepafe)", "Atividades": null, "Areas": "Orientação social e apoio material", "Area Princ": "Assistência Social", "Custo": null, "Endereco": "Estrada SP-50, 3080, Buquirinha 2", "Horario": null, "Telefone": "(12) 3948-1458", "Email": null, "Site": null, "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -45.839888, -22.973088 ] } },
{ "type": "Feature", "properties": { "Lat": -23.179440, "Long": -45.858926, "Nome": "CRAS – Centro de Referência de Assistência Social - Vila Industrial", "Atividades": null, "Areas": null, "Area Princ": "Assistência Social", "Custo": null, "Endereco": "Praça José Molina s\/n, Vila Industria", "Horario": null, "Telefone": "(12) 3912-3352 \/ (12) 3906-0217", "Email": null, "Site": null, "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -45.858926, -23.17944 ] } },
{ "type": "Feature", "properties": { "Lat": -23.202959, "Long": -45.901206, "Nome": "OBRA SOCIAL PADRE RODOLFO KOMOREK", "Atividades": "Capacitação de Domésticas, Babás e Formação da Mãe Gestante", "Areas": "Assistência Social", "Area Princ": "Assistência Social", "Custo": "R$ 12.000,00", "Endereco": "Rua Padre Rodolfo,28 - Vila Ema", "Horario": "de terça à sexta-feira, das 8h30 às 11h00, e das 14h30 às 17h00", "Telefone": "1239219460", "Email": "obrasocperodolfokomorek@hotmail.com", "Site": null, "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -45.901206, -23.202959 ] } },
{ "type": "Feature", "properties": { "Lat": -23.184024, "Long": -45.873293, "Nome": "Sociedade Holística Humanitária", "Atividades": "Atendimentos na área da Assistência Social, com orientações individuais e encaminhamentos aos serviços da Rede Pública e\/ou voluntários em áreas específicas.\nAtendimentos nas terapias naturais e energéticas, onde se aplicam Aromaterapia, Auriculoterapia,", "Areas": "Assistência Social, Crianças e Adolescentes, PCD (Pessoa com deficiência)", "Area Princ": "Assistência Social", "Custo": "Gratúito para pessoas pertencentes a famílias em vulnerabilidade social.", "Endereco": "Rua Capitão Raul Fagundes, 492 - Monte Castelo", "Horario": "de Segunda-Feira a Sexta-feira, das 08:00 às 12:00h e das 13:00 às 17:00h", "Telefone": "(12) 3942-3661 \/ (12) 98138-1353", "Email": "sociedadeholisticasjc.social@gmail.com", "Site": "Facebook: sociedade holistica humanitaria", "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -45.873293, -23.184024 ] } }
]
}
