var geojson_CriancasEAdolescentes = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "Lat": -23.213693, "Long": -45.809887, "Nome": "Clubeca – Clube da criança e do adolescente", "Atividades": null, "Areas": null, "Area Princ": "Criancas e Adolescentes", "Custo": null, "Endereco": "Rua Benedito de Paula Ferreira, 691 - Campos de São José - CEP 12.226-550 São José dos Campos - SP", "Horario": null, "Telefone": "(12) 3902-5355", "Email": "clubeca@clubeca.org.br", "Site": "www.clubeca.org.br", "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -45.809887, -23.213693 ] } },
{ "type": "Feature", "properties": { "Lat": -23.229998, "Long": -45.906146, "Nome": "Fundação Hélio Augusto de Souza - FUNDHAS", "Atividades": "As atividades socioeducativas são realizadas no contraturno da escola e, de preferência, em parceriacom ela, com a família, com a comunidade, numa rede de atenção à criança, ao adolescente e ao jovem. \nA proposta que norteia a FUNDHAS e todas as suas açõ", "Areas": "Cultura, Meio Ambiente, Saúde, Educação, Assistência Social, Crianças e Adolescentes", "Area Princ": "Criancas e Adolescentes", "Custo": "Não existe custo de atendimento a ser repassado aos atendidos pela instituição.", "Endereco": "Rua Santarém, 560 - Parque Industrial, São José dos Campos - SP", "Horario": "das 7h30 às 17h", "Telefone": "12 3932-0502", "Email": "andre.santos@fundhas.org.br", "Site": "http:\/\/www.fundhas.org.br", "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -45.906146, -23.229998 ] } },
{ "type": "Feature", "properties": { "Lat": -23.187998, "Long": -45.872325, "Nome": "Obra Social Célio Lemos", "Atividades": "No âmbito da OSCL atualmente funcionam: Projeto Bem Me Quer que atende aproximadamente  300 gestantes carentes por ano, o grupo  Amigos da Rua- Sopão distribui sopa, pães, roupas e cobertores toda semana nas ruas de sao jose dos campos e a Creche- CECOI", "Areas": "Educação, Crianças e Adolescentes", "Area Princ": "Criancas e Adolescentes", "Custo": null, "Endereco": "Rua Ana Gonçalves da Cunha no 30, Jardim Jussara. Sao Jose dos Campos\/SP", "Horario": "07h00 até 17h00 de segunda a sexta feira.", "Telefone": "12 3913 6883", "Email": "secretaria@oscl.org.br", "Site": "http:\/\/oscl.org.br\/", "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -45.872325, -23.187998 ] } }
]
}
