var geojson_MeioAmbiente = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "Lat": -23.203850, "Long": -45.810477, "Nome": "Cooperativa de Reciclagem São Vicente", "Atividades": null, "Areas": null, "Area Princ": "Meio Ambiente", "Custo": null, "Endereco": "Rua Estrada Dom José do Couto, 191 – Cajuru", "Horario": null, "Telefone": "(12) 3902-1882 \/ (12) 3431-1702", "Email": "coopsv@bol.com.br \/\/cooperativasv@gmail.com", "Site": "www.cooperativadereciclagem.wordpress.com\/", "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -45.810477, -23.20385 ] } },
{ "type": "Feature", "properties": { "Lat": -23.270245, "Long": -45.905678, "Nome": "Coopertech Resíduos Eletrônicos", "Atividades": "Reciclagem de Resíduos", "Areas": "Meio Ambiente", "Area Princ": "Meio Ambiente", "Custo": "Não há custos", "Endereco": "Rua Leonor de almeida r. souto 749", "Horario": "8:00 17:00", "Telefone": "(12)39662412", "Email": "coopertechresiduos@gmail.com", "Site": "www.coopertechresiduoseletronicos.org", "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -45.905678, -23.270245 ] } },
{ "type": "Feature", "properties": { "Lat": -23.191371, "Long": -45.891614, "Nome": "Ecomuseu Campos de São José", "Atividades": "Rodas de conversa, Feiras de saberes e fazeres, Inventário participativo, Rodas de bordados, Oficinas de Comunicação para jovens", "Areas": "Cultura, Meio Ambiente, Economia Solidária", "Area Princ": "Meio Ambiente", "Custo": "Não há custos", "Endereco": "Rua Luiz Jacinto, 265, 6º andar", "Horario": "Segunda a sexta feira, das 9:00 às 17:00", "Telefone": "39247318; 982645960; 996335597", "Email": "centrodeestudoscp@gmail.com, ecomuseusjc@gmail.com", "Site": "https:\/\/www.facebook.com\/ecomuseusjc\/", "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -45.891614, -23.191371 ] } },
{ "type": "Feature", "properties": { "Lat": -23.108235, "Long": -45.930343, "Nome": "PUPA", "Atividades": null, "Areas": null, "Area Princ": "Meio Ambiente", "Custo": null, "Endereco": "Estrada Municipal José Benedito Oliveira, 1865, Bairro dos Freitas, São José dos Campos-SP", "Horario": null, "Telefone": null, "Email": "pupa.permacultura@gmail.com", "Site": null, "Facebook": "Facebook: www.facebook.com\/pupa.permacultura" }, "geometry": { "type": "Point", "coordinates": [ -45.930343, -23.108235 ] } },
{ "type": "Feature", "properties": { "Lat": -23.223788, "Long": -45.883382, "Nome": "Recicalce", "Atividades": null, "Areas": null, "Area Princ": "Meio Ambiente", "Custo": null, "Endereco": "Rua Ipanema, 101 - Jd. Satélite - CEP: 12230-070 São José dos Campos - SP", "Horario": null, "Telefone": "(12) 3322-0050", "Email": "contato@recicalce.com.br", "Site": null, "Facebook": null }, "geometry": { "type": "Point", "coordinates": [ -45.883382, -23.223788 ] } },
{ "type": "Feature", "properties": { "Lat": -23.177642, "Long": -45.830241, "Nome": "Signi – Estratégias para sustentabilidade", "Atividades": null, "Areas": null, "Area Princ": "Meio Ambiente", "Custo": null, "Endereco": "Rua Alameda Harvey C. Weeks, 14 sala 63 - Bairro Vista Verde \/ CEP 12223-83", "Horario": null, "Telefone": "(12) 3307-6773 \/ (12) 3307-2707", "Email": null, "Site": "http:\/\/signi.com.br", "Facebook": "Facebook: www.facebook.com\/signiempresa" }, "geometry": { "type": "Point", "coordinates": [ -45.830241, -23.177642 ] } }
]
}
